# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/user
Accept: application/json

###

POST http://localhost:8080/post
Content-Type: application/json

{
  "id": "user4id",
  "name": "user4",
  "email": "user444@dgsw"
}

###

PUT http://localhost:8080/update
Content-Type: application/json

{
  "id": "user3id",
  "name": "user3",
  "email": "user33333333@dgsw"
}
###

DELETE http://localhost:8080/delete/user4id

###

GET http://localhost:8080/user/user2id
Accept: application/json
###